apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Servicio HTTP en Go con Dockerfile y manifests K8s
  tags:
    - go
    - kubernetes
  annotations:
    github.com/project-slug: ${{ (values.repoUrl | parseRepoUrl).owner }}/${{ (values.repoUrl | parseRepoUrl).repo }}
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
