apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-templates
  description: Índice central de todos los templates de la plataforma
spec:
  targets:
    - ./go-backend/template.yaml
    - ./go-lambda/template.yaml
    - ./nodejs-backend/template.yaml
    - ./rust-backend/template.yaml
    - ./react-frontend/template.yaml
    - ./angular-frontend/template.yaml
    - ./nodejs-library/template.yaml
    - ./rust-library/template.yaml
    - ./client-onboarding/template.yaml
    - ./client-project/template.yaml
    - ./client-service/template.yaml
