apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ${{ values.clientName }}
  title: ${{ values.clientTitle }}
  description: Portal de ${{ values.clientTitle }} — Documentación y proyectos
  annotations:
    backstage.io/techdocs-ref: dir:.
    clients.backstage.io/account-manager: ${{ values.accountManager }}
spec:
  type: client
  profile:
    displayName: ${{ values.clientTitle }}
  children: []
  members:
    - ${{ values.accountManager }}
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: ${{ values.clientName }}-${{ values.initialDomainSlug }}
  title: ${{ values.clientTitle }} — ${{ values.initialDomainTitle }}
  description: Dominio de negocio inicial para ${{ values.clientTitle }}
spec:
  owner: group:default/${{ values.clientName }}
